version: '2'

services:
  # Define a HOMER service
  homer:
    image: qxip/homer-metric-all:latest
    environment:
      INFLUXDB_URL: influxdb:8086
      DO_INFLUXDB: 1
      DO_KPI: 1
      DO_GEO: 1
      DO_KAMSTAT: 1
      DO_METHOD: 1
    volumes:
      - ./data/homer/mysql:/var/lib/mysql
    ports:
      - "9060:9060/udp"
      - "8080:80"
  # Define an InfluxDB service
  influxdb:
    depends_on:
      - "homer"
    image: influxdb:latest
    volumes:
      - ./data/influxdb:/var/lib/influxdb
    ports:
      - "8086:8086"
  # Define a Telegraf service
  telegraf:
    depends_on:
      - "influxdb"
    image: telegraf:latest
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
    links:
      - influxdb
    ports:
      - "8092:8092/udp"
      - "8094:8094"
      - "8125:8125/udp"
  # Define a Chronograf service
  chronograf:
    depends_on:
      - "influxdb"
    image: chronograf:latest
    environment:
      INFLUXDB_URL: http://influxdb:8086
      KAPACITOR_URL: http://kapacitor:9092
    ports:
      - "8888:8888"
    links:
      - influxdb
      - kapacitor
  # Define a Kapacitor service
  kapacitor:
    depends_on:
      - "influxdb"
    image: kapacitor:latest
    environment:
      KAPACITOR_HOSTNAME: kapacitor
      KAPACITOR_INFLUXDB_0_URLS_0: http://influxdb:8086
    links:
      - influxdb
    ports:
      - "9092:9092"
  # Define a service for using the influx CLI tool.
  # docker-compose run influxdb-cli
  influxdb-cli:
    depends_on:
      - "influxdb"
    image: influxdb:latest
    entrypoint:
      - influx
      - -host
      - influxdb
    links:
      - influxdb
  # Define a service for using the kapacitor CLI tool.
  # docker-compose run kapacitor-cli
  kapacitor-cli:
    depends_on:
      - "kapacitor"
    image: kapacitor:latest
    entrypoint: bash
    environment:
      KAPACITOR_URL: http://kapacitor:9092
    links:
      - kapacitor

# Define Asterisk service
#  asterisk:
#    network_mode: host
#    image: dougbtv/asterisk14
#    ports:
#      - "5060:5060/udp"
#      - "10001-10002:10001-10002/udp"
#    volumes:
#      - ./data/asterisk/pjsip.conf:/etc/asterisk/pjsip.conf
#      - ./data/asterisk/hep.conf:/etc/asterisk/hep.conf
#      - ./data/asterisk/asterisk1.rtp.conf:/etc/asterisk/rtp.conf
#      - ./data/asterisk/extensions.conf:/etc/asterisk/extensions.conf

# Define Elasticsearch service
#  elastic:
#    depends_on:
#      - "homer"
#    image: qxip/docker-kibi-steroids:latest
#    environment:
#      ES_USER: admin
#      ES_PASSWORD: admin
#    ports:
#      - "9200:9200"
#      - "5606:5606"


